services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=${PORT:-8080}
        - DATABASE_URL=${DATABASE_URL:-""}
    image: ${IMAGE_NAME:-anderson-poc-web}
    ports:
      - 8998:${PORT:-8080}
